In [5]:
import pandas as pd

In [6]:
fmr = pd.read_csv('/Users/user/Desktop/trying/fmr_done_rearranged.csv')
sec8 = pd.read_csv('/Users/user/Desktop/trying/Sec8_done_rearranged.csv')

In [7]:
sec8_fmr = pd.merge(sec8, fmr, 
                   on='_id', 
                   how='inner')
  
# displaying result
print(sec8_fmr)

               cbsasub         _id      state_name State_Alpha  \
0     METRO33860M33860   100199999         Alabama          AL
1     METRO19300M19300   100399999         Alabama          AL
2     NCNTY01005N01005   100599999         Alabama          AL
3     METRO13820M13820   100799999         Alabama          AL
4     METRO13820M13820   100999999         Alabama          AL
...                ...         ...             ...         ...
4751  METRO41980MM7440  7215199999     Puerto Rico          PR
4752  METRO49500M49500  7215399999     Puerto Rico          PR
4753  NCNTY78010N78010  7801099999  Virgin Islands          VI
4754  NCNTY78020N78020  7802099999  Virgin Islands          VI
4755  NCNTY78030N78030  7803099999  Virgin Islands          VI

                               Metro_Area_Name   county_town_name  \
0                           Montgomery, AL MSA     Autauga County
1                Daphne-Fairhope-Foley, AL MSA     Baldwin County
2                           Barbour County, AL     Barbour County
3     Birmingham-Hoover, AL HUD Metro FMR Area        Bibb County
4     Birmingham-Hoover, AL HUD Metro FMR Area      Blount County
...                                        ...                ...
4751  San Juan-Guaynabo, PR HUD Metro FMR Area  Yabucoa Municipio
4752                             Yauco, PR MSA    Yauco Municipio
4753                      St. Croix Island, VI          St. Croix
4754                       St. John Island, VI           St. John
4755                     St. Thomas Island, VI         St. Thomas

            County_Name  state  county  metro_x  ...  fmr2_17  fmr3_17  \
0        Autauga County      1       1        1  ...      822     1054
1        Baldwin County      1       3        1  ...      977     1422
2        Barbour County      1       5        0  ...      671      839
3           Bibb County      1       7        1  ...      866     1163
4         Blount County      1       9        1  ...      866     1163
...                 ...    ...     ...      ...  ...      ...      ...
4751  Yabucoa Municipio     72     151        1  ...      553      743
4752    Yauco Municipio     72     153        1  ...      432      555
4753          St. Croix     78      10        0  ...      910     1129
4754           St. John     78      20        0  ...     1430     1775
4755         St. Thomas     78      30        0  ...     1054     1308

      fmr4_17  fmr_0_22  fmr_1_22  fmr_2_22  fmr_3_22  fmr_4_22  \
0        1425       643       764       914      1156      1494
1        1634       772       777      1017      1348      1715
2         958       532       536       705       871       980
3        1298       765       820       943      1220      1316
4        1298       765       820       943      1220      1316
...       ...       ...       ...       ...       ...       ...
4751      924       428       466       538       719       868
4752      761       362       370       422       572       574
4753     1247       868       886      1082      1338      1467
4754     1960      1154      1368      1700      2101      2305
4755     1445       832      1001      1253      1549      1699

            metro_code  metro_y
0     METRO33860M33860        1
1     METRO19300M19300        1
2     NCNTY01005N01005        0
3     METRO13820M13820        1
4     METRO13820M13820        1
...                ...      ...
4751  METRO41980MM7440        1
4752  METRO49500M49500        1
4753  NCNTY78010N78010        0
4754  NCNTY78020N78020        0
4755  NCNTY78030N78030        0

[4756 rows x 30 columns]

In [10]:
sec8_fmr.head()

,cbsasub,_id,state_name,State_Alpha,Metro_Area_Name,county_town_name,County_Name,state,county,metro_x,...,fmr2_17,fmr3_17,fmr4_17,fmr_0_22,fmr_1_22,fmr_2_22,fmr_3_22,fmr_4_22,metro_code,metro_y
0,METRO33860M33860,100199999,Alabama,AL,"Montgomery, AL MSA",Autauga County,Autauga County,1,1,1,...,822,1054,1425,643,764,914,1156,1494,METRO33860M33860,1
1,METRO19300M19300,100399999,Alabama,AL,"Daphne-Fairhope-Foley, AL MSA",Baldwin County,Baldwin County,1,3,1,...,977,1422,1634,772,777,1017,1348,1715,METRO19300M19300,1
2,NCNTY01005N01005,100599999,Alabama,AL,"Barbour County, AL",Barbour County,Barbour County,1,5,0,...,671,839,958,532,536,705,871,980,NCNTY01005N01005,0
3,METRO13820M13820,100799999,Alabama,AL,"Birmingham-Hoover, AL HUD Metro FMR Area",Bibb County,Bibb County,1,7,1,...,866,1163,1298,765,820,943,1220,1316,METRO13820M13820,1
4,METRO13820M13820,100999999,Alabama,AL,"Birmingham-Hoover, AL HUD Metro FMR Area",Blount County,Blount County,1,9,1,...,866,1163,1298,765,820,943,1220,1316,METRO13820M13820,1

In [9]:
print(sec8_fmr.columns)

Index(['cbsasub', '_id', 'state_name', 'State_Alpha', 'Metro_Area_Name',
       'county_town_name', 'County_Name', 'state', 'county', 'metro_x',
       'median2017', 'l50_2_17', 'ELI_2_17', 'l80_2_17', 'median2022',
       'l50_2_22', 'ELI_2_22', 'l80_2_22', 'fmr0_17', 'fmr1_17', 'fmr2_17',
       'fmr3_17', 'fmr4_17', 'fmr_0_22', 'fmr_1_22', 'fmr_2_22', 'fmr_3_22',
       'fmr_4_22', 'metro_code', 'metro_y'],
      dtype='object')

In [14]:
yup = sec8_fmr.drop(['cbsasub','metro_x'], axis=1)

In [15]:
yup.head()

,_id,state_name,State_Alpha,Metro_Area_Name,county_town_name,County_Name,state,county,median2017,l50_2_17,...,fmr2_17,fmr3_17,fmr4_17,fmr_0_22,fmr_1_22,fmr_2_22,fmr_3_22,fmr_4_22,metro_code,metro_y
0,100199999,Alabama,AL,"Montgomery, AL MSA",Autauga County,Autauga County,1,1,59700,23900,...,822,1054,1425,643,764,914,1156,1494,METRO33860M33860,1
1,100399999,Alabama,AL,"Daphne-Fairhope-Foley, AL MSA",Baldwin County,Baldwin County,1,3,61500,24600,...,977,1422,1634,772,777,1017,1348,1715,METRO19300M19300,1
2,100599999,Alabama,AL,"Barbour County, AL",Barbour County,Barbour County,1,5,46100,18450,...,671,839,958,532,536,705,871,980,NCNTY01005N01005,0
3,100799999,Alabama,AL,"Birmingham-Hoover, AL HUD Metro FMR Area",Bibb County,Bibb County,1,7,63100,25250,...,866,1163,1298,765,820,943,1220,1316,METRO13820M13820,1
4,100999999,Alabama,AL,"Birmingham-Hoover, AL HUD Metro FMR Area",Blount County,Blount County,1,9,63100,25250,...,866,1163,1298,765,820,943,1220,1316,METRO13820M13820,1

In [18]:
print(yup.columns)

Index(['_id', 'state_name', 'State_Alpha', 'Metro_Area_Name',
       'county_town_name', 'County_Name', 'state', 'county', 'median2017',
       'l50_2_17', 'ELI_2_17', 'l80_2_17', 'median2022', 'l50_2_22',
       'ELI_2_22', 'l80_2_22', 'fmr0_17', 'fmr1_17', 'fmr2_17', 'fmr3_17',
       'fmr4_17', 'fmr_0_22', 'fmr_1_22', 'fmr_2_22', 'fmr_3_22', 'fmr_4_22',
       'metro_code', 'metro'],
      dtype='object')

In [17]:
yup.columns= ['_id', 'state_name', 'State_Alpha', 'Metro_Area_Name',
       'county_town_name', 'County_Name', 'state', 'county', 'median2017',
       'l50_2_17', 'ELI_2_17', 'l80_2_17', 'median2022', 'l50_2_22',
       'ELI_2_22', 'l80_2_22', 'fmr0_17', 'fmr1_17', 'fmr2_17', 'fmr3_17',
       'fmr4_17', 'fmr_0_22', 'fmr_1_22', 'fmr_2_22', 'fmr_3_22', 'fmr_4_22',
       'metro_code', 'metro']

In [20]:
# yup.to_csv("Sec8_fmr_done",index=False)